// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    [Migration("20250705035242_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.Guardia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Guardias");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.Invitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoQR")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaFinValidez")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicioValidez")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoInvitacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidenteId");

                    b.ToTable("Invitados");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.RegistroAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GuardiaId")
                        .HasColumnType("int");

                    b.Property<int?>("InvitadoId")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<string>("PlacasVehiculo")
                        .HasColumnType("longtext");

                    b.Property<int?>("ResidenteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAcceso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuardiaId");

                    b.HasIndex("InvitadoId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("RegistrosAcceso");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.Residente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("longblob");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Placas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidenteId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.Invitado", b =>
                {
                    b.HasOne("ControlDeAccesosDesktop.Models.Residente", "Residente")
                        .WithMany("Invitados")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.RegistroAcceso", b =>
                {
                    b.HasOne("ControlDeAccesosDesktop.Models.Guardia", "Guardia")
                        .WithMany("RegistrosAcceso")
                        .HasForeignKey("GuardiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlDeAccesosDesktop.Models.Invitado", "Invitado")
                        .WithMany("RegistrosAcceso")
                        .HasForeignKey("InvitadoId");

                    b.HasOne("ControlDeAccesosDesktop.Models.Residente", "Residente")
                        .WithMany("RegistrosAcceso")
                        .HasForeignKey("ResidenteId");

                    b.Navigation("Guardia");

                    b.Navigation("Invitado");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.Vehiculo", b =>
                {
                    b.HasOne("ControlDeAccesosDesktop.Models.Residente", "Residente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.Guardia", b =>
                {
                    b.Navigation("RegistrosAcceso");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.Invitado", b =>
                {
                    b.Navigation("RegistrosAcceso");
                });

            modelBuilder.Entity("ControlDeAccesosDesktop.Models.Residente", b =>
                {
                    b.Navigation("Invitados");

                    b.Navigation("RegistrosAcceso");

                    b.Navigation("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
